# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Basic Site Settings
title: "Bedru Yimam Ahmed | በድሩ ይማም አህመድ"
url: "https://bedruyimam.github.io"
baseurl: ""
site_theme: "mint"
repository: "BedruYimam/BedruYimam.github.io"

# Site Author
author:
  name: "Bedru Yimam"
  bio: "Lecturer and Researcher at Wollo University"
  email: "bedruy4@gmail.com"
  location: "Dessie, Ethiopia"
  employer: "Wollo University"
  github: "BedruYimam"

# MUST INCLUDE this section for pages to work
include:
  - _pages
  - _posts
  - _publications
  - _teaching
  - _talks
  - _portfolio

# Collections
collections:
  teaching:
    output: true
  publications:
    output: true
  talks:
    output: true
  portfolio:
    output: true

# Default layouts
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: publications
    values:
      layout: single

# Publication Categories (optional)
publication_category:
  journal:
    title: 'Journal Articles'
  conference:
    title: 'Conference Papers'
